# Generated by Django 4.2.7 on 2025-08-21 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('tilopay_card', 'Tarjeta (Tilopay)'), ('tilopay_yappy', 'Yappy (Tilopay)'), ('cash', 'Efectivo')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido'), ('refunded', 'Reembolsado'), ('cancelled', 'Cancelado'), ('expired', 'Expirado')], default='pending', max_length=20)),
                ('tilopay_transaction_id', models.CharField(blank=True, max_length=100)),
                ('tilopay_order_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('tilopay_session_token', models.TextField(blank=True)),
                ('tilopay_redirect_url', models.URLField(blank=True)),
                ('tilopay_payment_url', models.URLField(blank=True)),
                ('yappy_phone', models.CharField(blank=True, max_length=15)),
                ('yappy_qr_code', models.TextField(blank=True)),
                ('split_payment_data', models.JSONField(blank=True, default=dict)),
                ('split_responses', models.JSONField(blank=True, default=dict)),
                ('external_transaction_id', models.CharField(blank=True, max_length=100)),
                ('payment_data', models.JSONField(blank=True, default=dict)),
                ('webhook_received', models.BooleanField(default=False)),
                ('webhook_data', models.JSONField(blank=True, default=dict)),
                ('webhook_attempts', models.IntegerField(default=0)),
                ('payment_initiated_at', models.DateTimeField(blank=True, null=True)),
                ('payment_completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='TilopaySubmerchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submerchant_key', models.CharField(max_length=100, unique=True)),
                ('business_name', models.CharField(max_length=200)),
                ('business_email', models.EmailField(max_length=254)),
                ('business_phone', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_status', models.CharField(default='pending', max_length=50)),
                ('commission_percentage', models.DecimalField(decimal_places=4, default=0.15, max_digits=5)),
                ('accepts_cards', models.BooleanField(default=True)),
                ('accepts_yappy', models.BooleanField(default=True)),
                ('tilopay_response_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tilopay_submerchant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('tilopay_response', models.JSONField(blank=True, default=dict)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='payments.payment')),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commission_type', models.CharField(choices=[('platform', 'Plataforma'), ('driver', 'Conductor'), ('business', 'Negocio')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('percentage', models.DecimalField(decimal_places=4, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido'), ('reversed', 'Reversado')], default='pending', max_length=20)),
                ('tilopay_split_id', models.CharField(blank=True, max_length=100)),
                ('tilopay_split_status', models.CharField(blank=True, max_length=50)),
                ('payment_method_used', models.CharField(blank=True, max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_commissions', to='orders.order')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='payments.payment')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_commissions', to=settings.AUTH_USER_MODEL)),
                ('tilopay_submerchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.tilopaysubmerchant')),
            ],
        ),
    ]
