# Generated by Django 4.2.7 on 2025-08-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verification_code_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_verification_method',
            field=models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='sms', max_length=10),
        ),
    ]
